# Appendix A: The Relationship between the Prevalence Prior and Cue Validity

Cue validity is defined for a particular category--property pair (e.g., *mosquitos* and *carry malaria*), and relates to referent-prevalence (e.g., how many mosquitos carry malaria) via the prevalence of *carrying malaria* in other categories $k'$ by Bayes' Rule:
$$ P(k \mid f) = \frac{P(f \mid k) \cdot P(k)}{Z} $$
where $Z =  \sum_{k' \in K} P( f \mid k') \cdot P( k')$


The prevalence prior $P(p)$ (Eq. \ref{eq:L0}) is a probability distribution over prevalence for different categories $k'$.
<!-- For ease of exposition, let $x = p = P(f \mid k)$; that is, $P(x) = P(p)$. -->

\underline{Claim:} The normalizing constant for computing cue validity is equal to the expected value of the prevalence prior distribution: $\mathbb{E}[P(p)] = Z$

\underline{Proof:}

By the definition of the expectation of a distribution: 

\begin{eqnarray} \label{eq:expectation}
\mathbb{E}[P(p)] & = & \sum\limits_{p} p \cdot P(p) 
\end{eqnarray}

The probability of a prevalence $p$ can be decomposed into the prior probability of a category $k$ and the likelihood of the prevalence $p$ given that category $k$: $P(p) = P(p \mid k) \cdot P(k)$. 
We assume here, without loss of generality, that each category corresponds to one and only one prevalence $p$.
Thus, $P(p \mid k) = 1$ if $k \in K_p$, a set of categories that have a given prevalence: $K_p = \{k' : p_{k'} = p\}$. 
Then, consider the partition of the set of all categories $K$ into non-overlapping $K_p$.
Thus:

\begin{eqnarray} \label{eq:prevToKinds}
P(p) & = & \sum\limits_{k' \in K_p} P(p \mid k') \cdot P( k') \nonumber \\
     & = & \sum\limits_{k' \in K_p} P(k')
\end{eqnarray}

since $\forall k' \in K_{p}:  P(p \mid k') = 1$.
Returning to Eq. \ref{eq:expectation}, we have:

\begin{eqnarray} \label{eq:eq3}
\mathbb{E}[P(p)] & = & \sum\limits_{p} p \sum\limits_{k' \in K_p} P(k') \nonumber \\
                  & = & \sum\limits_{p} \sum\limits_{k' \in K_p} p \cdot P(k')
\end{eqnarray}

The set of all partitioned subsets $K_p$ is in a one-to-one correspondence with the set of all prevalences $p$. Thus, we have:

\begin{eqnarray} \label{eq:bijection}
  & = & \sum\limits_{K_p} \sum\limits_{k' \in K_p} p \cdot P( k')
\end{eqnarray}

Then, since $\cup_{p}{K_p} = K$, we have

\begin{eqnarray} \label{eq:partition}
  & = & \sum\limits_{k' \in K} p \cdot P( k') \nonumber \\ 
  & = & \sum\limits_{k' \in K} P(f \mid k') \cdot P( k') \nonumber \\ 
  & = & Z
\end{eqnarray}

$\square.$
