---
title: "comgen-outline"
author: "M. H. Tessler"
date: "5/24/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction

# The Bayesian Framework for Generlizations

# Communicating Generalizations with a Formal Model

- **Figure 1: L0(h|"silence") & L0(h|"generic") for uniform, are female, lays eggs, and has wings priors**

# Case Study 1: Generic Language

## Experiment 1: Endorsing generalizations about categories
### 1a: Measuring the prevalence prior with familiar kinds
### 1b: Endorsements

- **Figure 2: Endorsements vs. Prevalence, Prevalence + Cue Validity, Underspecified-threshold Model**
--- **include insets for L0 priors and posteriors**


## Experiment 2: Interpreting generalizations about categories
### 2a: Measuring the prevalence prior with unfamiliar kinds
### 2b: Interpretations

## Experiment 3: The asymmetry between truth conditions and interpretations (Replication and Extension of Cimpian et al., 2010)

## Discussion
  - Conceptual structure

# Case Study 2: Habitual Language

## Experiment 4: Endorsing and interpreting generalizations about events
### 4a: Measuring the propensity prior for event knowledge
### 4b: Endorsing generalizations about events
### 4c: Interpreting generalizations about events

## Experiment 5: Communcaiting predictive propensity

## Discussion
  - Predictive probabilities

# Case Study 3: Causal Language

## Experiment 6: 
### 6a: Prior elicitation / manipulation check
### 6b: Endorsement
### 6c: Interpretation


## Discussion

  - Prevalence prior is causally related to endorsement and interpretation
  
# General Discussion

## Comparison class
## Acquisition
## Conceptual structure
  -- Dangerousness
## Predictive propensities
## Relationship to extant theories
## Solutions to other philosophical puzzles

# Conclusion

